import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { createServer } from "./serve.mjs";
const require=createRequire(import.meta.url);
const { chromium }=require("playwright");

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const html=await fs.readFile(path.join(root,"index.html"),"utf8");
const schema=await fs.readFile(path.join(root,"backend","supabase-schema.sql"),"utf8");
const tests=[];const test=(name,fn)=>tests.push({name,fn});

test("inline JavaScript parses",()=>{const blocks=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).filter(Boolean);assert.equal(blocks.length,1);new vm.Script(blocks[0]);});
test("required package files exist",async()=>{for(const file of ["index.html","config.js","config.example.js","README.md","START-HERE.md","_headers","robots.txt","manifest.webmanifest","service-worker.js","assets/icon.svg","backend/supabase-schema.sql","docs/ARCHITECTURE.md","docs/ENVIRONMENTS.md","docs/Articulate-Daily-Customer-Guide-v3.03.docx","presentations/Articulate-Daily-Executive-Pitch-v3.03.pptx"]){await fs.access(path.join(root,file));}});
test("backend enforces per-user RLS",()=>{for(const rule of ["enable row level security","auth.uid()","for select","for insert","for update","for delete","revoke all","to authenticated"]){assert.match(schema,new RegExp(rule.replace(/[()]/g,"\\$&"),"i"));}});
test("security and validation safeguards are present",()=>{for(const token of ["MAX_FILE_BYTES","MAX_IMAGE_BYTES","MAX_IMPORT_BYTES","MAX_PROFILES","safeId","cleanText","csvEscape","deleteAllAppData","DELETE ALL","scheduleCloudSync","cloudAuthReady","already in sync","aria-live=\"polite\"","workerBlobURL:false","new URL(\"vendor/tesseract-worker.min.js\"","new URL(\"vendor/tesseract-core-simd-lstm.js\"","prepareOcrImage","redInk","tessedit_pageseg_mode","ocrTextPreview"]){assert.ok(html.includes(token),`Missing ${token}`);}});
test("heavy libraries are lazy and locally bundled",async()=>{assert.ok(html.includes("libraryScripts"));assert.equal((html.match(/<script src=\"https:/g)||[]).length,0);for(const file of ["pdf.min.js","pdf.worker.min.js","mammoth.browser.min.js","tesseract.min.js","tesseract-worker.min.js","tesseract-core-simd-lstm.js","tesseract-core-simd-lstm.wasm","eng.traineddata.gz","supabase.min.js"]){const stat=await fs.stat(path.join(root,"vendor",file));assert.ok(stat.size>1000,`${file} is unexpectedly small`);}});

let server,browser,page,origin;
test("frontend starts without console errors",async()=>{server=createServer();await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const port=server.address().port;origin=`http://127.0.0.1:${port}`;browser=await chromium.launch({headless:true});page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(origin,{waitUntil:"domcontentloaded"});await page.waitForTimeout(300);assert.deepEqual(errors,[]);assert.equal(await page.title(),"Articulate Daily | Advanced English for Work and Life");});
test("all seven application views navigate",async()=>{for(const id of ["dashboard","add","extract","practice","coach","library","settings"]){await page.locator(`.nav [data-view=\"${id}\"]`).click();assert.ok(await page.locator(`#${id}`).evaluate(el=>el.classList.contains("active")));assert.equal(await page.locator(`.nav [data-view=\"${id}\"]`).getAttribute("aria-current"),"page");}});
test("Settings appearance previews immediately and saves",async()=>{await page.locator('.nav [data-view="settings"]').click();await page.locator("#themeSelect").selectOption("dark");assert.equal(await page.locator("body").getAttribute("data-theme"),"dark");await page.locator("#fontSizeSelect").selectOption("large");assert.equal(await page.locator("body").getAttribute("data-font-size"),"large");await page.locator("#newTargetInput").fill("7");await page.locator("#savePreferencesBtn").click();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem("lexiflow_single_file_v1")));assert.equal(state.settings.theme,"dark");assert.equal(state.settings.fontSize,"large");assert.equal(state.settings.dailyTargets.newWords,7);});
test("profile creation is persisted",async()=>{await page.locator("#newProfileName").fill("Work English");await page.locator("#createProfileBtn").click();const names=await page.locator("#profileList strong").allTextContents();assert.ok(names.includes("Work English"));});
test("word creation and library search work",async()=>{await page.locator('.nav [data-view="add"]').click();await page.locator("#wordInput").fill("traceable");await page.locator("#meaningInput").fill("Able to be followed back to evidence.");await page.locator('#wordForm button[type="submit"]').click();await page.locator('.nav [data-view="library"]').click();await page.locator("#librarySearch").fill("traceable");assert.equal(await page.locator("#libraryList .word-card").count(),1);});
test("backup and CSV downloads contain safe data",async()=>{await page.locator('.nav [data-view="add"]').click();await page.locator("#wordInput").fill("formula-safe");await page.locator("#meaningInput").fill("=HYPERLINK(\"https://example.invalid\")");await page.locator('#wordForm button[type="submit"]').click();await page.locator('.nav [data-view="settings"]').click();const backupPromise=page.waitForEvent("download");await page.locator("#exportBtn").click();const backup=await backupPromise;const backupJson=JSON.parse(await fs.readFile(await backup.path(),"utf8"));assert.ok(backupJson.profiles);const csvPromise=page.waitForEvent("download");await page.locator("#exportCsvBtn").click();const csv=await csvPromise;const csvText=await fs.readFile(await csv.path(),"utf8");assert.match(csvText,/'=HYPERLINK/);});
test("document extraction groups and enriches vocabulary",async()=>{await page.route("https://api.dictionaryapi.dev/**",async route=>{const word=decodeURIComponent(new URL(route.request().url()).pathname.split("/").pop());await route.fulfill({contentType:"application/json",body:JSON.stringify([{word,meanings:[{partOfSpeech:"noun",definitions:[{definition:`A clear meaning for ${word}.`,example:`This is an everyday example using ${word}.`},{definition:`Another sense of ${word}.`,example:`The team used ${word} in a professional discussion.`}]}]}])});});await page.locator('.nav [data-view="extract"]').click();await page.locator("#fileInput").setInputFiles({name:"strategy.txt",mimeType:"text/plain",buffer:Buffer.from("Focus helps daily work. Planning supports reliable delivery. A meticulous review improves the strategic recommendation. We can raise the bar together.")});await page.locator("#fileStatus.success").waitFor({timeout:20000});const headings=await page.locator(".extract-group h4").allTextContents();for(const label of ["Simple Words","Medium Words","Strategic Words","Power Expressions"])assert.ok(headings.includes(label),`Missing ${label}`);assert.ok(await page.locator(".extract-word .extract-examples").count()>=2);await page.locator("#selectAllBtn").click();await page.locator("#addSelectedBtn").click();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem("lexiflow_single_file_v1")));const words=state.profiles[state.activeProfileId].words;assert.ok(words.some(w=>w.word==="focus"&&w.example2));assert.ok(words.some(w=>w.word==="raise the bar"&&w.category==="Power Expressions"));await page.unroute("https://api.dictionaryapi.dev/**");});
test("oversized images are rejected before OCR loads",async()=>{await page.locator('.nav [data-view="extract"]').click();await page.locator("#fileInput").setInputFiles({name:"too-large.png",mimeType:"image/png",buffer:Buffer.alloc(10*1024*1024+1)});assert.match(await page.locator("#fileStatus").innerText(),/too large|10 MB/i);});
test("file import controls can be reused",async()=>{assert.match(html,/importInput\.addEventListener\("change",async e=>\{await importBackup\(e\.target\.files\[0\]\);e\.target\.value=""/);assert.match(html,/importCsvInput\.addEventListener\("change",async e=>\{await importCsv\(e\.target\.files\[0\]\);e\.target\.value=""/);});
test("mobile layout exposes mobile navigation",async()=>{await page.setViewportSize({width:390,height:844});assert.ok(await page.locator(".mobile-nav").isVisible());assert.equal(await page.locator(".sidebar").isVisible(),false);await page.setViewportSize({width:1280,height:800});});
test("cloud integration remains non-blocking",async()=>{await page.locator('.nav [data-view="settings"]').click();assert.match(await page.locator("#cloudStatus").innerText(),/not configured|local saving|saved locally|signed out|sign in|sync|could not start/i);});
test("account recovery control is present",async()=>{assert.ok(await page.locator("#resetPasswordBtn").count());assert.match(html,/resetPasswordForEmail/);});
test("two-step delete-all flow clears local data",async()=>{let count=0;page.on("dialog",async dialog=>{count++;if(dialog.type()==="confirm")await dialog.accept();else if(dialog.type()==="prompt")await dialog.accept("DELETE ALL");else await dialog.dismiss();});await page.locator("#clearAllBtn").click();await page.waitForTimeout(100);const state=await page.evaluate(()=>JSON.parse(localStorage.getItem("lexiflow_single_file_v1")));assert.equal(Object.keys(state.profiles).length,1);assert.equal(Object.values(state.profiles)[0].words.length,0);assert.equal(count,2);});

let passed=0;try{for(const item of tests){try{await item.fn();passed++;console.log(`PASS ${item.name}`);}catch(error){console.error(`FAIL ${item.name}\n${error.stack||error}`);process.exitCode=1;break;}}}finally{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());}
console.log(`\n${passed}/${tests.length} tests passed`);if(passed!==tests.length)process.exitCode=1;
